# src/main/resources/application-dev.yml
spring:
  datasource:
    # 환경 변수 없으면 지정된 IP의 DB로 붙어
    url: jdbc:postgresql://34.158.208.117:5432/msa_pay_db?currentSchema=pay
    username: app_user
    password: user1234
    driver-class-name: org.postgresql.Driver # 포스트그레 드라이버 사용

  rabbitmq:
    host: localhost # 메시지 큐 호스트 설정
    port: 5672 # 래빗MQ 기본 포트
    username: msa_mq # 큐 접속 계정
    password: mq1234 # 큐 접속 비번

  jpa:
    hibernate:
      ddl-auto: validate # 테이블은 건드리지 말고 구조만 검증해
    show-sql: true # 실행되는 SQL 로그를 보여줘
    properties:
      hibernate:
        "[format_sql]": true # SQL 로그를 보기 좋게 정렬해

mybatis:
  mapper-locations: classpath:mappers/**/*.xml # 매퍼 XML 위치 지정
  type-aliases-package: com.example.payment.dto # DTO 패키지 경로 별칭

kakao:
  pay:
    secret-key: dev_secret_key_here # 개발용 시크릿 키
    cid: TC0ONETIME # 테스트용 가맹점 코드
    # 로컬 Nginx Gateway 또는 직접 접속 주소
    approval-url: http://localhost:8083/payment/success
    cancel-url: http://localhost:8083/payment/cancel
    fail-url: http://localhost:8083/payment/fail
    base-url: https://open-api.kakaopay.com