# src/main/resources/application.properties

spring.application.name=payment-service

# 기본적으로 dev 프로파일을 실행 (운영 배포 시 환경 변수로 prod 덮어쓰기)
spring.profiles.active=dev

# 서버 포트 설정 (로컬 Nginx 라우팅 및 Prod 컨테이너 포트와 일치하도록 8083 사용)
server.port=8083