# src/main/resources/application-dev.properties

# PostgreSQL 설정
# 환경 변수가 없으면 localhost 기준으로 동작하도록 기본값 설정
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://34.158.208.117:5432/msa_pay_db?currentSchema=pay}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# RabbitMQ 설정
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER:msa_mq}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:mq1234}

# JPA 및 Hibernate 설정
# DDL 스크립트를 별도로 관리하므로 테이블 자동 생성 대신 검증(validate)만 수행
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

