# src/main/resources/application-prod.properties

# GCP 운영 환경(Server 2) 배포 시 docker-compose.yml의 environment 값을 주입받아 동작
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 레빗MQ 설정
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# 운영 환경에서는 성능 및 안정성을 위해 DDL 자동 변경 및 SQL 로깅 비활성화
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# MyBatis Mapper XML 위치 설정
mybatis.mapper-locations=classpath:mappers/**/*.xml
# DTO 패키지 경로 별칭 설정 (XML에서 패키지명 생략 가능)
mybatis.type-aliases-package=com.example.payment.dto.response